language: php

php:
  - 8.3
  - 8.4

dist: jammy

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --no-interaction --prefer-dist --no-progress

stages:
  - lint
  - analysis
  - test

jobs:
  include:
    - stage: lint
      name: "Code Standards"
      php: 8.3
      script:
        - composer cs

    - stage: test
      name: "PHPUnit Tests (PHP 8.3)"
      php: 8.3
      script:
        - composer test

    - stage: test
      name: "PHPUnit Tests (PHP 8.4)"
      php: 8.4
      script:
        - composer test

    - stage: analysis
      name: "Static Analysis"
      php: 8.3
      script:
        - composer require --dev phpstan/phpstan ^1.0
        - vendor/bin/phpstan analyse src --level=5
