language: php

php:
  - 8.0
  - 8.1

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

install:
  - composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
  - composer require drupal/coder
  - phpcs --config-set installed_paths $TRAVIS_BUILD_DIR/vendor/drupal/coder/coder_sniffer

script:
  - find . -name \*.php -exec php -l {} \;
  - phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,info --ignore=node_modules,bower_components,vendor .
