language: php

php:
  - 7.4
  - 8.0
  - 8.1
  - 8.2

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --no-interaction --prefer-dist --no-progress

script:
  - composer test
  - composer cs

jobs:
  include:
    - stage: "Code Coverage"
      php: 8.1
      script:
        - composer test -- --coverage-clover=coverage.xml
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: "Static Analysis"
      php: 8.1
      script:
        - composer require --dev phpstan/phpstan ^1.0
        - vendor/bin/phpstan analyse src --level=5

notifications:
  email: false